[RESEAU]
SSID_1=VOTRE_WIFI
PSK_1=VOTRE_PSK_WIFI_EN_HEXADECIMAL

; SSID_2 et SSID_3 sont facultatifs.
; Ne mettez jamais votre mot de passe Wi-Fi dans ce fichier.

[SYSTEME]
FUSEAU_HORAIRE=EST5EDT,M3.2.0,M11.1.0
VOLUME_DEFAUT=12