[env:freenove_esp32_s3_wroom]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino
monitor_speed = 115200

build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D USER_SETUP_LOADED=1
    -D ILI9341_2_DRIVER=1
    -D TFT_RGB_ORDER=TFT_BGR
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_INVERSION_ON=1
    -D TFT_MISO=13
    -D TFT_MOSI=11
    -D TFT_SCLK=12
    -D TFT_CS=10
    -D TFT_DC=46
    -D TFT_RST=-1
    -D TFT_BL=45
    -D TFT_BACKLIGHT_ON=HIGH
    -D SPI_FREQUENCY=40000000
    -D USE_HSPI_PORT=1
    
    ; --- LES POLICES DE CARACTÈRES (LE CORRECTIF EST ICI) ---
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D SMOOTH_FONT=1

lib_deps =
    bodmer/TFT_eSPI
    https://github.com/schreibfaul1/ESP32-audioI2S.git#3.0.12